name: PPAP test

on:
  push:
    branches:
      - main

jobs:
  ppap-sync:
    name: PPAP sync
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ClutterNews/nodejs-crawler
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          token: ${{ secrets.GH_PAT }}
          cache: "npm"
          node-version-file: ".nvmrc"

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Run test
        run: node src/functions/githubAuth.js
