name: Reset Data

on:
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout data
        uses: actions/checkout@v4
        with:
          repository: ClutterNews/kh-data
          token: ${{ secrets.GH_PAT }}

      - name: Reset
        run: rm -rf *.db

      - name: Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m ':white_check_mark: Reset Data'
          git push origin main -f
