name: Test

on:
  workflow_dispatch:
  # push:
    # branches:
    #   - main

jobs:
  pre:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout crawl
        uses: actions/checkout@v4
        with:
          repository: ClutterNews/nodejs-clutter
          token: ${{ secrets.GH_PAT }}

      - name: Checkout data
        uses: actions/checkout@v4
        with:
          repository: ClutterNews/kh-data
          path: src/databases/data
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          token: ${{ secrets.GH_PAT }}
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Run npm install
        run: npm install

      - name: Running
        run: node src/functions/githubUploadMetaImage.js
        # run: node src/functions/test.js
